#!/bin/bash

ROOT=/home/msk_jenkins/artifacts

cd $ROOT

for job in * ; do

  cd $ROOT/$job

  for label in * ; do

    cd $ROOT/$job/$label

    for buildType in * ; do

      cd $ROOT/$job/$label/$buildType
      KEEP=`ls -rt | tail -n 1`

      for build in *; do

        if [ "$build" != "$KEEP" ]; then
          rm -rf $ROOT/$job/$label/$buildType/$build
        fi

      done

    done

  done

done
